### ISSUE TITLE
example data

### ISSUE THREAD

**Issue by xuezhicang** [KCallaghan/FlowFill#1]
Could you upload a example data?

My topography data is converted from the DEM. The filled results seem to be wrong. The elevation range of original DEM is from -2400 to 3300 meter, but the filled elevations are extreme small (smaller than -1*10^15) or extreme large. I guess that the organization of my input data format has some problems.
Would you provide a example of .nc data, so I can identify the correct data format.  

Thank you for your help.

**Comment by KCallaghan** [comment]
Hi, could you tell me more about the input settings you used? What starting runoff value did you use? 
I am working on some example data but perhaps we can try to diagnose this problem so long.

**Comment by xuezhicang** [comment]
Thank you for your answer. I have submitted my input setting at Issue #2
